spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_rh
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "gestion-rh-secret-key-for-academic-project-change-me"
    expiration-ms: 86400000
